#!/usr/bin/env node
/**
 * wiki-index - regenerate .project-wiki/index.md from page frontmatter.
 *
 * index.md is a synthesized catalog, not hand-fed content (twt-wiki-define
 * Step 1) - which makes it exactly the kind of file a model should not
 * rewrite freehand: a dropped line silently orphans a page. This script
 * compiles it deterministically, the way gen-docs.mjs compiles SKILLS.md.
 *
 * Each page's line comes from its own frontmatter: `title`, `status`,
 * `updated`, and the optional one-line `summary` (the curator writes it when
 * creating or touching a page; the filename stands in when absent). The
 * judgment stays with the curator - this script only catalogs.
 *
 * Usage: node tools/wiki-index.mjs <projectDir>
 * Curator-invoked: fails loudly (exit 1) instead of exiting 0 like the
 * phase-run harvester.
 */
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

function fail(msg) {
  console.error(`wiki-index: ${msg}`);
  process.exit(1);
}

function frontmatter(path) {
  let text;
  try { text = readFileSync(path, 'utf8'); } catch (e) { return {}; }
  const lines = text.split(/\r?\n/);
  if (lines[0] !== '---') return {};
  const fm = {};
  for (let i = 1; i < lines.length && lines[i] !== '---'; i++) {
    const m = /^(title|status|updated|summary):\s*(.*)$/.exec(lines[i]);
    if (m) fm[m[1]] = m[2].trim();
  }
  return fm;
}

// One catalog line per page: title, the curator's one-line summary when the
// page carries one, and (status, updated) so agents can weigh it at a glance.
function pageLine(wiki, relPath, fallbackTitle, defaultSummary) {
  const fm = frontmatter(join(wiki, relPath));
  const title = fm.title || fallbackTitle;
  const summary = fm.summary || defaultSummary || '';
  const meta = [fm.status, fm.updated].filter(Boolean).join(', ');
  let line = `- [${title}](${relPath})`;
  if (summary) line += ` - ${summary}`;
  if (meta) line += ` (${meta})`;
  return line;
}

const CORE = [
  ['overview.md', 'Overview', 'the project in one page'],
  ['facts.md', 'Facts', 'the canonical ledger'],
  ['open-questions.md', 'Open questions', 'what is still unresolved'],
  ['sources.md', 'Sources', 'all evidence'],
  ['glossary.md', 'Glossary', 'terms and banned words'],
];

const COLLECTIONS = [
  ['decisions', 'what was decided, and why'],
  ['ideas', 'ideas not yet scoped'],
  ['entities', 'client, audience, competitors - and durable concepts'],
  ['analyses', 'saved answers worth keeping'],
];

function main() {
  const projectDir = process.argv[2];
  if (!projectDir) fail('usage: node tools/wiki-index.mjs <projectDir>');
  const wiki = join(projectDir, '.project-wiki');
  if (!existsSync(wiki)) fail('no .project-wiki/ - run /twt-wiki first');

  const today = new Date().toISOString().slice(0, 10);
  const out = [];
  out.push('---');
  out.push('title: Index');
  out.push('type: overview');
  out.push('status: current');
  out.push(`updated: ${today}`);
  out.push('sources: []');
  out.push('tags: []');
  out.push('---');
  out.push('');
  out.push('# Index');
  out.push('');
  out.push('The catalog of this wiki. Start here.');
  out.push('');
  out.push('<!-- GENERATED by tools/wiki-index.mjs from page frontmatter - do not edit by hand.');
  out.push('     A page\'s line comes from its own title/status/updated/summary fields. -->');
  out.push('');
  out.push('## Core');
  for (const [rel, title, def] of CORE) {
    if (existsSync(join(wiki, rel))) out.push(pageLine(wiki, rel, title, def));
  }
  out.push('');
  out.push('## Collections');

  let pageCount = 0;
  for (const [dir, blurb] of COLLECTIONS) {
    let files = [];
    try {
      files = readdirSync(join(wiki, dir))
        .filter((f) => f.endsWith('.md'))
        .sort();
    } catch (e) { /* collection folder absent - listed as empty */ }
    pageCount += files.length;
    out.push(`- \`${dir}/\` - ${blurb} (${files.length} ${files.length === 1 ? 'page' : 'pages'})`);
    for (const f of files) {
      out.push('  ' + pageLine(wiki, `${dir}/${f}`, f.replace(/\.md$/, '')));
    }
  }

  out.push('');
  out.push('## Machinery');
  out.push('- [Inbox](inbox.md) - raw captured decisions, awaiting curation');
  out.push('- [Log](log.md) - append-only history');
  out.push('- [Operating manual](AGENTS.md) - how to maintain this wiki');
  out.push('');

  writeFileSync(join(wiki, 'index.md'), out.join('\n'), 'utf8');
  console.log(`index.md regenerated: ${pageCount} collection page(s) cataloged.`);
}

main();
