#!/usr/bin/env node
// Regenerate SKILLS.md, architecture.md, skills/<cat>/README.md, and the
// README.md marked block from skill frontmatter + Intent blocks.
//
// This is the deterministic engine behind /twt-marketplace-docs. It runs only
// in the marketplace repo (author-time), so it has no runtime-delivery concern.
//
//   node tools/gen-docs.mjs            regenerate all derived docs
//   node tools/gen-docs.mjs --check    exit 1 if any derived doc is stale (CI)
//
// No dependencies — a tiny purpose-built frontmatter reader, not a full YAML lib.

import { readFileSync, writeFileSync, readdirSync, existsSync } from "node:fs";
import { join, dirname, basename } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const SKILLS_DIR = join(ROOT, "skills");

const CHECK = process.argv.includes("--check");

const CATEGORY_DESC = {
  content: "Skills for fetching and processing external content",
  elementor: "Skills for building Hello Elementor child themes and widgets",
  meta: "Skills that manage the twt marketplace itself",
  brand: "Skills for capturing or deriving brand identity (palette, voice, tone, values)",
  spec: "Skills for capturing the north-star specification (vision, functional scope, visual & motion direction)",
  positioning: "Skills for defining audience, value propositions, and promotion priorities",
  ia: "Skills for defining sitemap and functional scope (information architecture)",
  curation: "Skills for deciding keep/skip/elevate and building page outlines",
  "pre-design": "Phase 1 wrapper that orchestrates the full pre-design pipeline",
  "design-system": "Cross-phase shared design system: tokens, CSS export, and foundations preview",
  component: "Component library specs and a token-driven HTML gallery",
  layout: "Per-page responsive layout specs (sections, component slots, content map)",
  mockup: "Fully-responsive plain-HTML/CSS hi-fi page mockups from real content",
  design: "Phase 2 wrapper that orchestrates the full design pipeline",
  html: "Skills for building a dependency-free static HTML/CSS site (scaffold + token-driven page builder)",
  develop: "Phase 3 full-path wrapper: promote the Phase-2 design into the chosen build target",
  "roast-express": "Phase 3 express entry: from a Figma link, build the design system and jump to development",
  qa: "Static-analysis QA audits of built output (content, design, a11y, links, Elementor hygiene) + gaps punch-list",
  "roast-full": "Master orchestrator that runs the full pre-design→design→development→QA pipeline with approval pauses",
  status: "Pipeline freshness check: flag artifacts that are older than the inputs they were derived from",
  search: "Standalone site-search utilities — find a string across a website's pages and report where it appears",
};

const SKILLS_HDR = "<!-- AUTO-GENERATED by /twt-marketplace-docs · do not edit by hand · regenerate after any frontmatter change -->";
const README_HDR = "<!-- AUTO-GENERATED by /twt-marketplace-docs · do not edit by hand -->";

// ---- parsing -------------------------------------------------------------

function parseFrontmatter(text) {
  const lines = text.split(/\r?\n/);
  if (lines[0].trim() !== "---") return null;
  let end = -1;
  for (let i = 1; i < lines.length; i++) if (lines[i].trim() === "---") { end = i; break; }
  if (end === -1) return null;

  const fm = { inputs: [], reads: [], writes: [], dependencies: { hard: [], soft: [] } };
  let ctx = null; // 'inputs' | 'reads' | 'writes' | 'dep.hard' | 'dep.soft'
  let inDeps = false;

  for (let i = 1; i < end; i++) {
    const line = lines[i];
    const item = line.match(/^\s+-\s+(.*)$/);
    if (item && ctx) {
      if (ctx === "dep.hard") fm.dependencies.hard.push(item[1].trim());
      else if (ctx === "dep.soft") fm.dependencies.soft.push(item[1].trim());
      else fm[ctx].push(item[1].trim());
      continue;
    }
    // top-level key
    let m = line.match(/^([a-z_]+):\s*(.*)$/);
    if (m) {
      const key = m[1], val = m[2];
      inDeps = key === "dependencies";
      if (["inputs", "reads", "writes"].includes(key)) { ctx = key; continue; }
      if (key === "dependencies") { ctx = null; continue; }
      ctx = null;
      if (key === "name" || key === "category" || key === "description" || key === "version") fm[key] = val.trim();
      else if (key === "accepts_arguments") fm.accepts_arguments = val.trim() === "true";
      continue;
    }
    // nested key under dependencies (2-space indent)
    m = line.match(/^\s\s(hard|soft):\s*(.*)$/);
    if (m && inDeps) {
      const val = m[2].trim();
      if (val === "[]" || val === "") { ctx = m[1] === "hard" ? "dep.hard" : "dep.soft"; }
      else ctx = m[1] === "hard" ? "dep.hard" : "dep.soft";
      continue;
    }
  }
  return fm;
}

function parseIntent(text) {
  const all = text.split(/\r?\n/);
  // Scope to the Intent block only — from '## Intent' to its closing '---'.
  // (Skills like /twt-marketplace-docs repeat **Non-goals:** etc. in body
  // templates, which must not leak into the parsed Intent.)
  let s = -1, e = all.length;
  for (let i = 0; i < all.length; i++) if (all[i].trim() === "## Intent") { s = i + 1; break; }
  if (s !== -1) for (let i = s; i < all.length; i++) if (all[i].trim() === "---") { e = i; break; }
  const lines = s === -1 ? all : all.slice(s, e);

  const out = { purpose: "", non_goals: [], success_criteria: [] };
  const collectBullets = (start) => {
    const items = [];
    for (let i = start; i < lines.length; i++) {
      const l = lines[i];
      if (/^\s*-\s+/.test(l)) { items.push(l.replace(/^\s*-\s+/, "")); continue; }
      if (l.trim() === "") continue;
      break; // a non-bullet, non-blank line ends the list
    }
    return items;
  };
  for (let i = 0; i < lines.length; i++) {
    const l = lines[i];
    if (l.startsWith("**Purpose:**")) out.purpose = l.replace("**Purpose:**", "").trim();
    else if (l.startsWith("**Non-goals:**")) out.non_goals = collectBullets(i + 1);
    else if (l.startsWith("**Success criteria:**")) out.success_criteria = collectBullets(i + 1);
  }
  return out;
}

// ---- load all skills -----------------------------------------------------

const skills = [];
const warnings = [];
for (const cat of readdirSync(SKILLS_DIR, { withFileTypes: true })) {
  if (!cat.isDirectory()) continue;
  const dir = join(SKILLS_DIR, cat.name);
  for (const f of readdirSync(dir)) {
    if (!f.endsWith(".md") || f === "README.md") continue;
    const path = join(dir, f);
    const text = readFileSync(path, "utf8");
    const fm = parseFrontmatter(text);
    if (!fm) { warnings.push(`${path}: no frontmatter`); continue; }
    const intent = parseIntent(text);
    const REQ = ["name", "category", "description", "version", "inputs", "reads", "writes"];
    for (const k of REQ) {
      const v = fm[k];
      if (v === undefined || (Array.isArray(v) && v.length === 0 && k !== "writes" && k !== "reads")) {
        warnings.push(`${path}: missing field ${k}`);
      }
    }
    if (fm.accepts_arguments === undefined) warnings.push(`${path}: missing field accepts_arguments`);
    if (fm.name !== basename(f, ".md")) warnings.push(`${path}: name '${fm.name}' != filename`);
    if (fm.category !== cat.name) warnings.push(`${path}: category '${fm.category}' != folder '${cat.name}'`);
    skills.push({ path, category: cat.name, ...fm, intent });
  }
}
skills.sort((a, b) => a.name.localeCompare(b.name));
const byName = new Map(skills.map((s) => [s.name, s]));

function isInternalOrchestratedRole(s) {
  const match = s.name.match(/^(.*)-(define|validate)$/);
  return Boolean(match && byName.has(match[1]));
}

const publicSkills = skills.filter((s) => !isInternalOrchestratedRole(s));

// reverse deps
for (const s of skills) {
  s.hard_consumers = skills.filter((o) => (o.dependencies.hard || []).includes(s.name)).map((o) => o.name).sort();
  s.soft_consumers = skills.filter((o) => (o.dependencies.soft || []).includes(s.name)).map((o) => o.name).sort();
}

const list = (arr) => (arr && arr.length ? arr.join(", ") : "none");
const bullets = (arr) => (arr && arr.length ? arr.map((x) => `- ${x}`).join("\n") : "");
const bulletsOrNone = (arr) => (arr && arr.length ? bullets(arr) : "- (none)");
const nodeId = (n) => n.replace(/-/g, "_");

// ---- SKILLS.md -----------------------------------------------------------

function renderSkills() {
  const idx = publicSkills.map((s) => `| [/${s.name}](#${s.name}) | ${s.category} | ${s.description} |`).join("\n");
  const head =
`${SKILLS_HDR}

# twt Skills — Command Reference

All commands use the \`/twt-\` prefix. Type the command name in Claude Code to run it.

## Index

| command | category | description |
|---------|----------|-------------|
${idx}`;

  const sections = publicSkills.map((s) => {
    const writes = bulletsOrNone(s.writes);
    return `## /${s.name}

**Category:** ${s.category}
**Version:** ${s.version}
**Accepts arguments:** ${s.accepts_arguments ? "yes" : "no"}

${s.intent.purpose}

**Inputs:**
${bulletsOrNone(s.inputs)}

**Dependencies:**
- Hard: ${list(s.dependencies.hard)}
- Soft: ${list(s.dependencies.soft)}

**Reads:**
${bulletsOrNone(s.reads)}

**Writes:**
${writes}

**Non-goals:**
${bullets(s.intent.non_goals)}

**Success criteria:**
${bullets(s.intent.success_criteria)}`;
  });

  return `${head}

---
${sections.join("\n\n---\n\n")}
`;
}

// ---- architecture.md -----------------------------------------------------

function renderArch() {
  const nodes = skills.map((s) => `    ${nodeId(s.name)}["/${s.name}"]:::skill`).join("\n");
  const edges = [];
  for (const s of skills) {
    for (const d of s.dependencies.hard || []) if (byName.has(d)) edges.push(`    ${nodeId(d)} --> ${nodeId(s.name)}`);
    for (const d of s.dependencies.soft || []) if (byName.has(d)) edges.push(`    ${nodeId(d)} -.-> ${nodeId(s.name)}`);
  }

  const cats = [...new Set(skills.map((s) => s.category))].sort();
  const byCat = cats
    .map((c) => `### ${c}\n\n` + skills.filter((s) => s.category === c).map((s) => `- /${s.name} - ${s.description}`).join("\n"))
    .join("\n\n");

  const details = skills
    .map((s) => {
      const writesRows = s.writes && s.writes.length ? "\n" + s.writes.map((w) => `| ${w} |  |`).join("\n") : "";
      return `### /${s.name}

**Category:** ${s.category}
**Version:** ${s.version}

**Inputs:**
${bulletsOrNone(s.inputs)}

**Dependencies:**
- Hard: ${list(s.dependencies.hard)}
- Soft: ${list(s.dependencies.soft)}

**Feeds into:**
- Hard consumers: ${list(s.hard_consumers)}
- Soft consumers: ${list(s.soft_consumers)}

**Reads:**
${bulletsOrNone(s.reads)}

**Writes:**
| Path | Notes |
|------|-------|${writesRows}`;
    })
    .join("\n\n");

  const depRows = skills.map((s) => `| /${s.name} | ${list(s.dependencies.hard)} | ${list(s.dependencies.soft)} |`).join("\n");

  const segs = new Set();
  for (const s of skills) for (const w of s.writes || []) {
    const m = w.match(/^\.twt-artifacts\/([^/\s]+)/);
    if (m) segs.add(m[1]);
  }
  const namespace = [...segs].sort().map((x) => `  ${x}/`).join("\n");

  return `${SKILLS_HDR}

# twt — Skill Architecture

Auto-generated dependency and artifact map. For editorial workflows, see [WORKFLOWS.md](WORKFLOWS.md).

## Skill dependency graph

\`\`\`mermaid
flowchart TB
${nodes}
${edges.join("\n")}

    classDef skill fill:#0D1B2A,stroke:#1DB89C,stroke-width:2px,color:#FAFAF8;
\`\`\`

## Skills by category

${byCat}

## Per-skill details

${details}

## Cross-skill dependency table

| Skill | Hard deps | Soft deps |
|-------|-----------|-----------|
${depRows}

## Artifact namespace summary

\`\`\`
.twt-artifacts/
${namespace}
\`\`\`
`;
}

// ---- category READMEs ----------------------------------------------------

function renderCatReadme(cat) {
  const rows = publicSkills.filter((s) => s.category === cat).map((s) => `| /${s.name} | ${s.description} |`).join("\n");
  const desc = CATEGORY_DESC[cat] || `Skills in the ${cat} category.`;
  return `${README_HDR}

# ${cat}

${desc}

## Skills

| command | description |
|---------|-------------|
${rows}
`;
}

// ---- README.md marked block ---------------------------------------------

function updateReadmeBlock() {
  const p = join(ROOT, "README.md");
  if (!existsSync(p)) return "README.md: not found — skipped";
  // Normalize to LF; the write loop reapplies the file's EOL uniformly.
  // (Splicing an LF block into CRLF text would otherwise yield \r\r\n.)
  let txt = readFileSync(p, "utf8").replace(/\r\n/g, "\n");
  const START = "<!-- TWT_SKILLS_TABLE_START -->";
  const END = "<!-- TWT_SKILLS_TABLE_END -->";
  if (!txt.includes(START) || !txt.includes(END)) return "README.md: TWT_SKILLS_TABLE markers not found — skipped";
  const rows = publicSkills.map((s) => `| /${s.name} | ${s.category} | ${s.description} |`).join("\n");
  const block = `${START}\n| command | category | description |\n|---------|----------|-------------|\n${rows}\n${END}`;
  const next = txt.replace(new RegExp(`${START}[\\s\\S]*?${END}`), block);
  return { p, next, label: "README.md (marked block)" };
}

// ---- write or check ------------------------------------------------------

const targets = [
  { p: join(ROOT, "SKILLS.md"), next: renderSkills(), label: "SKILLS.md" },
  { p: join(ROOT, "architecture.md"), next: renderArch(), label: "architecture.md" },
];
for (const cat of [...new Set(skills.map((s) => s.category))]) {
  targets.push({ p: join(SKILLS_DIR, cat, "README.md"), next: renderCatReadme(cat), label: `skills/${cat}/README.md` });
}
const rb = updateReadmeBlock();
if (typeof rb === "string") warnings.push(rb);
else targets.push(rb);

// Match each file's existing line endings (repo is CRLF on Windows) so the
// regen diff stays content-only and doesn't flip every line to LF.
const repoCrlf = existsSync(join(ROOT, "SKILLS.md")) && readFileSync(join(ROOT, "SKILLS.md"), "utf8").includes("\r\n");
const withEol = (s, crlf) => (crlf ? s.replace(/\n/g, "\r\n") : s);

let stale = 0;
for (const t of targets) {
  const cur = existsSync(t.p) ? readFileSync(t.p, "utf8") : null;
  const crlf = cur != null ? cur.includes("\r\n") : repoCrlf;
  const next = withEol(t.next, crlf);
  if (cur === next) continue;
  stale++;
  if (CHECK) { console.log(`STALE: ${t.label}`); continue; }
  writeFileSync(t.p, next);
  console.log(`${cur === null ? "created" : "updated"}: ${t.label}`);
}

console.log(`\nSkills indexed: ${skills.length}`);
console.log(`Categories: ${[...new Set(skills.map((s) => s.category))].sort().join(", ")}`);
console.log(`Warnings: ${warnings.length ? "\n  - " + warnings.join("\n  - ") : "(none)"}`);
if (CHECK && stale) { console.log(`\n${stale} file(s) stale — run: node tools/gen-docs.mjs`); process.exit(1); }
if (!CHECK) console.log(`\n${stale} file(s) ${stale ? "regenerated" : "already current"}.`);
